import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer"
import HomePage from "./components/HomePage";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Quiktis",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} px-12`}>
        <Header/>
          <HomePage />
        <Footer />
      </body>
    </html>
  );
}
